# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
#  - echo "-->> Preparing build environment..."
  build:
#    - echo "-->> Setting up working directory..."
    working_directory: ~/repo
#    - echo "-->> Installing node and mongo Docker images..."
    docker:
      # Docker images for node and mongodb
      - image: circleci/node:7.10
      - image: circleci/mongo:3.4.4
    steps:
      - checkout
      # Download and cache dependencies
#      - echo "-->> Restoring node dependency caches (if any)..."
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install all needed dependencies
#      - echo "-->> Installing npm dependencies..."
      - run:
          name: Install npm dependencies
          command: npm install
      # Save the cache for faster builds
      - echo "-->> Saving node dependency caches (if any)..."
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Start node app
#      - run:
#          name: Start app
#          command: npm start

  test:
    docker:
      # Docker test images for node and mongodb
      - image: circleci/node:7.10
      - image: circleci/mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: app tests
          command: npm test
      - run:
          name: Generate test coverage report
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: develop